# Generated by Django 5.2.17 on 2026-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('modules', models.JSONField(blank=True, default=list, help_text='Module keys this role can access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='sales', help_text="'superadmin', 'admin', or a Role.key", max_length=30),
        ),
    ]
