# Generated by Django 5.2.17 on 2026-08-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, help_text='e.g. Mikocheni, Dar es Salaam', max_length=120)),
                ('interest', models.CharField(choices=[('fiber_installation', 'Fiber Installation'), ('router_setup', 'Router Setup'), ('wifi_extender', 'Wi-Fi Extender'), ('mikrotik_voucher', 'Mikrotik Voucher System'), ('access_point', 'Access Point'), ('fiber_onu_ont', 'Fiber ONU/ONT'), ('power_backup', 'Power Backup (UPS)'), ('support', 'Maintenance & Support')], default='router_setup', max_length=32)),
                ('source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('referral', 'Referral'), ('walk_in', 'Walk-in')], default='website', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(default='Field Technician', help_text='Job title, e.g. Field Technician', max_length=120)),
                ('access_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('tint', models.PositiveSmallIntegerField(default=1, help_text='1-6, controls avatar color')),
                ('active', models.BooleanField(default=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, help_text='Base monthly salary in TZS', max_digits=12)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('customer_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('fiber_installation', 'Fiber Installation'), ('router_setup', 'Router Setup'), ('wifi_extender', 'Wi-Fi Extender'), ('mikrotik_voucher', 'Mikrotik Voucher'), ('access_point', 'Access Point'), ('fiber_onu_ont', 'Fiber ONU/ONT'), ('power_backup', 'Power Backup'), ('support', 'Support')], default='router_setup', max_length=32)),
                ('status', models.CharField(choices=[('not_started', 'To do'), ('in_progress', 'In progress'), ('review', 'Review'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='not_started', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ops.technician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='ops.technician')),
            ],
            options={
                'ordering': ['done', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text="First day of the pay period's month")),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', max_length=8)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='ops.technician')),
            ],
            options={
                'ordering': ['-period', 'technician__name'],
                'unique_together': {('technician', 'period')},
            },
        ),
    ]
