# Generated by Django 5.2.17 on 2026-08-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel_transport', 'Fuel & Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('marketing', 'Marketing'), ('maintenance', 'Equipment Maintenance'), ('office_supplies', 'Office Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ops.technician')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('item_name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('router', 'Router'), ('wifi_extender', 'Wi-Fi Extender'), ('mikrotik', 'Mikrotik'), ('access_point', 'Access Point'), ('fiber_onu_ont', 'Fiber ONU/ONT'), ('power_backup', 'Power Backup (UPS)'), ('cable', 'Cable & Accessories'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='ordered', max_length=10)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='ops.supplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
