# Generated by Django 5.2.17 on 2026-08-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_supplier_expense_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fiber_installation', 'Fiber Installation'), ('router_setup', 'Router Setup'), ('wifi_extender', 'Wi-Fi Extender'), ('mikrotik_voucher', 'Mikrotik Voucher'), ('access_point', 'Access Point'), ('fiber_onu_ont', 'Fiber ONU/ONT'), ('power_backup', 'Power Backup (UPS)'), ('support', 'Support'), ('product_sale', 'Product Sale'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=8)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=16)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='ops.installationjob')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
