# Generated by Django 5.2.17 on 2026-08-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('router', 'Router'), ('wifi_extender', 'Wi-Fi Extender'), ('mikrotik', 'Mikrotik'), ('access_point', 'Access Point'), ('fiber_onu_ont', 'Fiber ONU/ONT'), ('power_backup', 'Power Backup (UPS)'), ('cable', 'Cable & Accessories'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(default='pcs', help_text='e.g. pcs, box, meter', max_length=20)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Flag as low stock at or below this quantity')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='ops.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='ops.product'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(help_text='Positive = stock in, negative = stock out')),
                ('reason', models.CharField(choices=[('purchase', 'Stock Received'), ('sale', 'Stock Sold'), ('adjustment', 'Manual Adjustment')], max_length=12)),
                ('reference', models.CharField(blank=True, help_text='PO/invoice number, if applicable', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ops.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
