# Generated by Django 5.2.17 on 2026-08-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_branch_expense_branch_installationjob_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technician',
            name='access_role',
            field=models.CharField(blank=True, help_text='A Role.key, or blank for none', max_length=30),
        ),
    ]
