# Generated by Django 5.2.17 on 2026-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('deleted', 'Deleted'), ('login', 'Logged In'), ('login_failed', 'Failed Login'), ('logout', 'Logged Out')], max_length=15),
        ),
    ]
