# Generated by Django 5.2.17 on 2026-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_paymentmethod_purchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='When the remaining balance is due in full (for partially paid sales).', null=True),
        ),
    ]
